warehouse/urls.py
from django.contrib import admin
from django.urls import path

from store import views
from store.views import PartListView, PartCreateView, PartUpdateView, PartDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, CategoryDetailView, LocationCreateView, \
    LocationListView, LocationUpdateView, LocationDeleteView, LandingPageView, LocationDetailView, PartDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    #parts
    path('parts/', PartListView.as_view(), name='part-list'),
    path('parts/create/', PartCreateView.as_view(), name='part-create'),
    path('parts/<int:pk>/update/', PartUpdateView.as_view(), name='part-update'),
    path('parts/<int:pk>/delete/', PartDeleteView.as_view(), name='part-delete'),
    path('parts/<int:pk>/', PartDetailView.as_view(), name='part-detail'),
    #categories
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    #locations
    path('locations/', LocationListView.as_view(), name='locations-list'),
    path('locations/create/', LocationCreateView.as_view(), name='locations-create'),
    path('locations/<int:pk>/update/', LocationUpdateView.as_view(), name='locations-update'),
    path('locations/<int:pk>/delete/', LocationDeleteView.as_view(), name='locations-delete'),
    path('locations/<int:pk>/', LocationDetailView.as_view(), name='locations-detail'),
    #api list
    path('api/categories/', views.CategoryList.as_view()),
    path('api/locations/', views.LocationList.as_view()),
    path('api/parts/', views.PartList.as_view()),
    #api details
    path('api/parts/<int:pk>/', views.PartDetail.as_view()),
    path('api/categories/<int:pk>/', views.CategoryDetail.as_view()),
    path('api/locations/<int:pk>/', views.LocationDetail.as_view()),
    #api delete
    path('api/parts/<int:pk>/delete/', views.PartDelete.as_view()),
    path('api/categories/<int:pk>/delete/', views.CategoryDelete.as_view()),
    path('api/locations/<int:pk>/delete/', views.LocationyDelete.as_view()),
    #api post
    path('api/categories/create/', views.CategoryCreate.as_view()),
    path('api/locations/create/', views.LocationCreate.as_view()),
    path('api/parts/create/', views.PartCreate.as_view()),

]

store/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.core.exceptions import ValidationError

class Category(models.Model):
    name = models.CharField(max_length=100)
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Location(models.Model):
    room = models.CharField(max_length=100)
    bookcase = models.CharField(max_length=100)
    shelf = models.CharField(max_length=100)
    cupboard = models.CharField(max_length=100)
    column = models.CharField(max_length=100)
    row = models.CharField(max_length=100)

@receiver(pre_delete, sender=Location)
def prevent_delete_location(sender, instance, **kwargs):
    if instance.part_set.exists():
        raise ValidationError("Nie można usunąć lokalizacji z przypisanymi częściami.")

class Part(models.Model):
    serial_number = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    price = models.FloatField()
    location = models.ForeignKey(Location, on_delete=models.CASCADE)


@receiver(pre_delete, sender=Category)
def prevent_delete_parent_category(sender, instance, **kwargs):
    if instance.part_set.exists():
        raise ValidationError("Nie można usunąć kategorii z przypisanymi częściami.")

    if instance.parent_category and Category.objects.filter(parent_category=instance.parent_category).exclude(pk=instance.pk).exists():
        raise ValidationError("Nie można usunąć kategorii rodzica, która ma inne podkategorie.")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sample Form</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/category_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Delete Category</h1>
        <p>Are you sure you want to delete this category?</p>
        <form method="post" class="float-left">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Yes" name="answer">
            <a href="{% url 'category-list' %}" class="btn btn-secondary">No</a>
        </form>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/category_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 mb-3">
        <div class="row">
            {% for category in categories %}
                <div class="card shadow" style="width: 20rem; height: 10rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ category.name }} <br>
                            <small>{{ category.parent_category }}</small>
                        </h5>
                        <a href="/categories/{{ category.id }}/delete/" class="btn btn-danger mx-4">Delete</a>
                        <a href="/categories/{{ category.id }}/update/" class="btn btn-primary mx-4">Update</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <a href="{% url 'category-create' %}" class="btn btn-primary mx-4">Create next</a>
    <a href="{% url 'category-list' %}" class="btn btn-primary mx-4">Back</a>
{% endblock %}

templates/category_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Create category</h2>
        <form action="{% url 'category-create' %}" method="POST" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label class="control-label" for="id_name">Category Name</label>
                <input type="text" class="form-control" id="id_name" name="name">
            </div>
            <div class="form-group">
                <label class="control-label" for="id_parent_category">Parent Category</label>
                <select class="form-control" id="id_parent_category" name="parent_category">
                    <option value="" selected>None</option>
                    {% for category in categories %}
                        {% if not category.parent_category %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="text-center">
                <button class="btn btn-primary waves-effect waves-light" id="btn-submit">Save</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/category_list.html
{% extends 'base.html' %}
{% block content %}
        <div class="container mt-5 mb-3">
        <h1>Categories list:</h1>
        {% for category in categories %}
            <ul>View details
                <a href="{% url 'category-detail' category.id %}" class="btn btn-primary mx-4">{{ category.name }} </a>
            </ul>
        {% endfor %}<br>
        </div>
    <a href="{% url 'category-create' %}" class="btn btn-primary mx-4">Create next</a>
    <a href="{% url 'landing-page' %}" class="btn btn-primary mx-4">Back</a>
{% endblock %}

templates/category_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Update part</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Modify</button>
        </form>

    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample Form</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<table class="table table-dark table-striped">
    <thead>
    <tr class="text-center">
        <th scope="col"></th>
        <th scope="col">Part</th>
        <th scope="col">Category</th>
        <th scope="col">Location</th>
    </tr>
    </thead>
    <tbody>
    <tr class="text-center">
        <th scope="row"></th>
        <td><a href="{% url 'part-create' %}" class="btn btn-primary mx-4">create</a>
        </td>
        <td>
            <a href="{% url 'category-create' %}" class="btn btn-primary mx-4">create</a>
        </td>
        <td>
            <a href="{% url 'locations-create' %}" class="btn btn-primary mx-4">create</a>
        </td>
    </tr>
    <tr class="text-center">
        <th scope="row"></th>
        <td><a href="{% url 'part-list' %}" class="btn btn-primary mx-4">list</a>
        </td>
        <td>
            <a href="{% url 'category-list' %}" class="btn btn-primary mx-4">list</a>
        </td>
        <td>
            <a href="{% url 'locations-list' %}" class="btn btn-primary mx-4">list</a>
        </td>
    </tr>
    </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/location_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <p> Are you shure you want to delete?</p>
    <form method="post" class="float-left">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Yes" name="answer">
        <input type="submit" class="btn btn-primary" value="No" name="answer">
    </form>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/location_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 mb-3">
        <div class="row">
            {% for location in locations %}
                <div class="card shadow" style="width: 20rem; height: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ location.room }} <br>
                            <small>
                                <b>Bookcase:</b> {{ location.bookcase }}<br>
                                <b>Shelf:</b> {{ location.shelf }}<br>
                                <b>Cupboard:</b> {{ location.cupboard }}<br>
                                <b>Column:</b> {{ location.column }}<br>
                                <b>Row:</b> {{ location.row }}
                            </small>
                        </h5>
                        <p>
                            <a href="/locations/{{ location.id }}/delete/" class="btn btn-danger
                                            mx-4">Delete</a>
                            <a href="/locations/{{ location.id }}/update/" class="btn btn-primary mx-4">Update</a></p>
                    </div>

                </div>

            {% endfor %}
        </div>
    </div>
    <a href="{% url 'category-create' %}" class="btn btn-primary mx-4">Create next</a>
    <a href="{% url 'locations-list' %}" class="btn btn-primary mx-4">Back</a>
{% endblock %}

templates/location_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Create Location</h2>
        <form action="{% url 'locations-create' %}" method="POST" class="form-horizontal">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_room">Location Room</label>
                        <div class="col-sm-8">
                            {{ form.room }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_bookcase">Location Bookcase</label>
                        <div class="col-sm-8">
                            {{ form.bookcase }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_shelf">Location Shelf</label>
                        <div class="col-sm-8">
                            {{ form.shelf }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_cupboard">Location Cupboard</label>
                        <div class="col-sm-8">
                            {{ form.cupboard }}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_column">Location Column</label>
                        <div class="col-sm-8">
                            {{ form.column }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_row">Location Row</label>
                        <div class="col-sm-8">
                            {{ form.row }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-primary waves-effect waves-light" id="btn-submit">Save</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/location_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 mb-3">
        <h1>Location list:</h1>
        {% for location in locations %}
            <ul>View details:
                <a href="{% url 'locations-detail' location.id %}" class="btn btn-primary mx-4">
                    s{{ location.id }}</a>
            </ul>
        {% endfor %}
    </div><br>
    <a href="{% url 'locations-create' %}" class="btn btn-primary mx-4">Create next</a>
    <a href="{% url 'landing-page' %}" class="btn btn-primary mx-4">Back</a>
{% endblock %}

templates/part_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 mb-3">
        <div class="row">
            {% for part in parts %}
                <div class="col-lg-4 my-4">
                    <div class="card shadow" style="width: 20rem; height: 25rem;">
                        <div class="card-body">
                            <h5 class="card-title">Part name: {{ part.name }} <br>
                                <small>Serial number: {{ part.serial_number }}<br>
                                    Description: {{ part.description }} <br>
                                    Category: {{ part.category }} <br>
                                    Quantity: {{ part.quantity }} <br>
                                    Price: {{ part.price }} <br>
                                    Location room: {{ part.location.room }}<br>
                                    <ul>
                                        Bookcase: {{ part.location.bookcase }}<br>
                                        Shelf: {{ part.location.shelf }}<br>
                                        Cupboard: {{ part.location.cupboard }}<br>
                                        Column: {{ part.location.column }}<br>
                                        Row: {{ part.location.row }}
                                    </ul>
                                </small>
                            </h5>
                            <a href="/parts/{{ part.id }}/delete/" class="btn btn-danger mx-4">Delete</a>
                            <a href="/parts/{{ part.id }}/update/" class="btn btn-primary mx-4">Update</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <a href="{% url 'part-create' %}" class="btn btn-primary mx-4">Create next</a>
    <a href="{% url 'part-list' %}" class="btn btn-primary mx-4">Back</a>
{% endblock %}

templates/part_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Create part</h2>
        <form action="{% url 'part-create' %}" method="POST" class="form-horizontal">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_name">Part Name</label>
                        <div class="col-sm-8">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_serial_number">Serial Number</label>
                        <div class="col-sm-8">
                            {{ form.serial_number }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_description">Description</label>
                        <div class="col-sm-8">
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_quantity">Quantity</label>
                        <div class="col-sm-8">
                            {{ form.quantity }}
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_category">Category</label>
                        <div class="col-sm-8">
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="id_price">Price</label>
                        <div class="col-sm-8">
                            {{ form.price }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="id_location">Location</label>
                        <select class="form-control" id="id_location" name="location">

                            {% for location in locations %}
                                <option value="{{ location.id }}">
                                    {{ location.room }}, {{ location.bookcase }}, {{ location.shelf }},
                                    {{ location.cupboard }}, {{ location.columns }}, {{ location.row }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-primary waves-effect waves-light" id="btn-submit">Save</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/part_list.html
{% extends 'base.html' %}
{% block content %}
        <div class="container mt-5 mb-3">
        <h1>Parts list:</h1>
        {% for part in parts %}
            <ul>View details
                <a href="{% url 'part-detail' part.id %}" class="btn btn-primary mx-4">{{ part.name }} </a>
            </ul>
        {% endfor %}<br>
        </div>
    <a href="{% url 'category-create' %}" class="btn btn-primary mx-4">Create next</a>
    <a href="{% url 'landing-page' %}" class="btn btn-primary mx-4">Back</a>
{% endblock %}